const data =[
    {id:0,
        Heading:"Echoes of Defeat:A Personal Reflection on India’s 2023 World Cup Loss", 
        Description:"The first one read, “India's loss in the 2023 World Cup final has echoes of West Indies' defeat in the 1983 World Cup final.” The parallels are .....",
        image:"Virat.png"},
    {id:1,
        Heading:"Chandrayaan-3 : India's Imperatives for Space Leadership", 
        Description:"Chandrayaan-3's exploration of the lunar south pole signifies a new era in India's space endeavors.This achievement presents an opportunity ...",
        image:"chandrayan.png"},
    {id:2,
        Heading:"UN DESA Policy Brief No. 153: India overtakes China as the world’s most populous country", 
        Description:"In April 2023, India's population is expected to reach 1,425,775,850 people, matching and then surpassing the population of mainland China ( ...",
        image:"UN.png"},
    {id:3,
        Heading:"Teetotaller-Turned-Liquor Baron Lalit Khaitan Is India’s Newest Billionaire", 
        Description:"The 80-year-old liquor magnate is chairman of the $380 million (revenue) Delhi-based Radico Khaitan, best known for such beverages as 8 PM ...",
        image:"India's newest.png"},
    {id:4,
        Heading:"Google Year in Search 2023: Who were the most searched people in India", 
        Description:"As the year 2023 comes to a close, Google has once again revealed the most searched personalities in India. From Bollywood stars to cricket......",
        image:"google.png"},
    {id:5,
        Heading:"Top 10 Most Searched Recipes in India in 2023", 
        Description:"Mango pickle was the most searched recipe in India in 2023. The traditional Indian condiment, made with raw, unripe green mangoes, spices...",
        image:"recipe.png"},
    {id:6,
        Heading:"When will the violence in Manipur end?", 
        Description:"Peace will not come without acknowledging state complicity and making reparations, all while ensuring safety for the Zo community.",
        image:"manipur.png"},
    {id:7,
        Heading:"Uttarakhand tunnel collapse: Rescuers free 41 trapped workers", 
        Description:"The workers were stuck for two weeks after a part of a tunnel they were working in collapsed.",
        image:"tunnel.png"},
    {id:8,
        Heading:"Odisha train accident: Fifty bodies unclaimed weeks after India crash", 
        Description:"More than 50 bodies remain unclaimed a month after a deadly train crash killed at least 293 people in India. The accident took place on 2 ...",
        image:"odisha train.png"},
]
export default data;